/**
 * One-off asset pipeline: generates responsive WebP variants of the hero
 * illustration, builds a correctly sized social preview image, and self-hosts
 * the Google Fonts used by the site so the render-blocking request disappears.
 *
 * Run with: node scripts/optimize-assets.mjs
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const assets = resolve(root, "src/assets");
const publicDir = resolve(root, "public");
// Fonts live under src/ so the bundler fingerprints them and they inherit the
// immutable cache headers that hashed assets get.
const fontsDir = resolve(assets, "fonts");

const NAVY = { r: 11, g: 30, b: 61 };

async function buildImages() {
  const source = resolve(assets, "hero-illustration.jpg");
  const input = await readFile(source);

  for (const width of [480, 768, 1024]) {
    const out = resolve(assets, `hero-illustration-${width}.webp`);
    await sharp(input).resize({ width }).webp({ quality: 78, effort: 6 }).toFile(out);
    console.log(`wrote ${out}`);
  }

  // Social cards are cropped to roughly 1.91:1; compositing onto the brand navy
  // avoids the square illustration being cut off at the top and bottom.
  const inner = await sharp(input).resize({ width: 560, height: 560 }).png().toBuffer();
  const og = resolve(publicDir, "og-image.jpg");
  await sharp({
    create: { width: 1200, height: 630, channels: 3, background: NAVY },
  })
    .composite([{ input: inner, gravity: "east", top: 35, left: 600 }])
    .jpeg({ quality: 82, mozjpeg: true })
    .toFile(og);
  console.log(`wrote ${og}`);
}

// Weight ranges (rather than discrete weights) make Google return a single
// variable woff2 per family instead of one file per weight.
const FONT_CSS_URL =
  "https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,400..700&family=Manrope:wght@400..700&display=swap";

// Google serves modern woff2 only when the request looks like a current browser.
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36";

async function buildFonts() {
  await mkdir(fontsDir, { recursive: true });

  const res = await fetch(FONT_CSS_URL, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`Google Fonts responded ${res.status}`);
  const css = await res.text();

  const blocks = css.split("@font-face").slice(1);
  const kept = [];

  for (const block of blocks) {
    // Only the base latin subset is needed; latin-ext and the rest add weight
    // for glyphs this site never renders.
    if (!/unicode-range:[^;]*U\+0000-00FF/.test(block)) continue;

    const family = block.match(/font-family:\s*'([^']+)'/)?.[1];
    const weight = block.match(/font-weight:\s*([^;]+);/)?.[1]?.trim();
    const style = block.match(/font-style:\s*([^;]+);/)?.[1]?.trim() ?? "normal";
    const url = block.match(/src:\s*url\(([^)]+)\)/)?.[1];
    if (!family || !url) continue;

    const file = `${family.toLowerCase().replace(/\s+/g, "-")}-variable.woff2`;

    const fontRes = await fetch(url, { headers: { "User-Agent": UA } });
    if (!fontRes.ok) throw new Error(`Font download failed: ${url}`);
    await writeFile(resolve(fontsDir, file), Buffer.from(await fontRes.arrayBuffer()));
    console.log(`wrote ${file}`);

    kept.push({ family, weight, style, file });
  }

  const out = kept
    .map(
      ({ family, weight, style, file }) => `@font-face {
  font-family: "${family}";
  font-style: ${style};
  font-weight: ${weight};
  font-display: swap;
  src: url("./assets/fonts/${file}") format("woff2");
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA,
    U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193,
    U+2212, U+2215, U+FEFF, U+FFFD;
}`,
    )
    .join("\n\n");

  const target = resolve(root, "src/fonts.css");
  await writeFile(target, `/* Generated by scripts/optimize-assets.mjs — do not edit by hand. */\n${out}\n`);
  console.log(`wrote ${target}`);
}

await buildImages();
await buildFonts();
